### ISSUE TITLE
Allow skipping of beautification

### ISSUE THREAD

**Issue by domenic** [domenic/ecmarkdown#12]
If an Ecmarkup embedder is just going to beautify afterward anyway, it'd be a shame to slow things down for no real purpose.

**Comment by bterlson** [comment]
Do we have to make it an option?

**Comment by bterlson** [comment]
Per IRC: No! Nuke it.

I found that beautify is EXTREMELY slow. Beautify is about 80% of the time spent with the hand written parser in #22.
