### ISSUE TITLE
Don't auto-code-ify "strings" in paragraphs

### ISSUE THREAD

**Issue by domenic** [domenic/ecmarkdown#20]
Instead, smart quote them (#17).

**Comment by bterlson** [comment]
Worth noting that I believe this works with the fragment entry point currently as escapeHtml turns " into *&quot;"

**Comment by domenic** [comment]
An alternate approach is to stop auto-codeifying strings everywhere. It doesn't gain you all that much.

**Comment by littledan** [comment]
Why not auto-code-ify strings? I have been using an old version of ecmark{up,down} so I didn't actually see this feature yet.

**Comment by domenic** [comment]
Inside paragraphs you often use quotes for things that are not strings. Inside algorithms though it's almost always a real string. But e.g. check out the overzealous codeification in https://arv.github.io/ecmascript-object-observe/#solution

Other examples of where codeification would be wrong:

- http://www.ecma-international.org/ecma-262/6.0/#sec-syntactic-grammar
- http://www.ecma-international.org/ecma-262/6.0/#sec-grammar-notation (a lot)
- http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-language-types-number-type

etc.

**Comment by jmdyck** [comment]
You could decide that only straight-quoted strings are auto-code-ified, and curly-quoted strings are left as-is. So in cases of overzealous codeification, change straight quotes to curlies.

**Comment by domenic** [comment]
Yeah, but then people have to type curlies (or use entities).

**Comment by bterlson** [comment]
I think we should just get rid of codification. Surrounding with backticks is ok. I'm confused at why it's backticks and not stars though. Why is true a value and a string code? See also #9.

**Comment by bterlson** [comment]
Getting rid of codification will also make #17 easier probably.

**Comment by rwaldron** [comment]
> Surrounding with backticks is ok.

Thats what I figured anyway? I don't think I've yet encountered the issues being discussed.

**Comment by littledan** [comment]
OK, SGTM

**Comment by bterlson** [comment]
@Domenic I plan to simply remove this. Will send PR.
