### ISSUE TITLE
inconsistencies with ecmarkup

### ISSUE THREAD

**Issue by jmdyck** [domenic/ecmarkdown#23]
README.md has some inconsistencies with respect to the ecmarkup document:

-- It refers to the elements `<emu-val>` and `<emu-const>`, which are not defined.

 -- It has examples of `<emu-nt>` with the attribute `params`, but the ecmarkup doc says `Params` with a capital 'P'.

**Comment by domenic** [comment]
@bterlson I think this is all Ecmarkup's fault (lacking/incorrect docs). Also ecmarkup needs some emu-const sans-serif styles.
