### ISSUE TITLE
Blank line leads to blank section

### ISSUE THREAD

**Issue by littledan** [domenic/ecmarkdown#38]
In an emu-clause, if there is a blank line after the h1 tag, the initial text in that section is omitted.

**Comment by bterlson** [comment]
This is likely an Emu bug rather than an emd bug :)

But, can you show me an example of what you mean? Also make sure to try with version 2.0.3 :)

**Comment by littledan** [comment]
Oh sorry, this is probably misfiled.

```
<emu-clause>
<h1>Foobar</h1>

Baz
</emu-clause>
```

The result has an empty body and just a heading.
