### ISSUE TITLE
__proto__ converts to <var></var>proto__

### ISSUE THREAD

**Issue by jmdyck** [domenic/ecmarkdown#44]
ecmarkdown converts, e.g.
```
  <p>__proto__</p>
```
to
```
  <p><var></var>proto__</p>
```
ecmarkdown should know that a variable can't have an empty name, and thus that an underscore immediately followed by another underscore can't be the start of an UnderscoreFormat.

And similarly with other format-characters*, though none of them occurs doubled in the ES6 spec. Or at least, not in a context that triggers this behavior.

(*Actually, `<p>||</p>` causes ecmarkdown's parser to throw a TypeError.)

**Comment by bterlson** [comment]
This is fixed.
