### ISSUE TITLE
Double-decoding issue leading to difficulty to output  `<!` in emu-grammar

### ISSUE THREAD

**Issue by claudepache** [domenic/ecmarkdown#46]
I don’t know if this is an issue of ecmarkdown proper or an interaction with some pre- or post-processing.

When working on the ES spec, I've noticed that the following code will not work as expected:

    <emu-grammar>A :: `<!`</emu-grammar> 
    <emu-grammar>A :: `&lt;!`</emu-grammar> 
    <emu-grammar>A :: `&lt;&#x21;`</emu-grammar> 

It works when double-encoding one of the characters:

    <emu-grammar>A :: `<&amp;#x21;`</emu-grammar> 
    <emu-grammar>A :: `&amp;lt;!`</emu-grammar>

That makes very cumbersome to output the `<!` token in a grammar.

**Comment by bterlson** [comment]
This is some interaction between emu and gmd. Not sure why I need to escape input to gmd, but I do. Fixed in latest Emu release, though!

**Comment by bterlson** [comment]
I was too hasty. The issue appears to be that `<!` is gmd syntax for lookahead doesn't contain and it gets confused. I'll file a bug over there (and revert the emu change).

**Comment by bterlson** [comment]
Actually, two issues. For some reason HTML parsers see the following as a comment:

```
<emu-grammar>A :: `<!`</emu-grammar> 
```

Removing that case, the other issue is that grammarkdown wasn't emitting escaped html. I've already reported that bug and got it fixed, but didn't update the emu package.json to pick up the new version. I've made the appropriate updates and this is now ACTUALLY closed :)
