### ISSUE TITLE
Documents hang forever if there is no newline at the end

### ISSUE THREAD

**Issue by domenic** [domenic/ecmarkdown#49]
As of f7da4966041d95657272c65e22245559bfe63c5c this bug has manifested. Not a big deal since documents should probably have a newline but worth fixing.

**Comment by bterlson** [comment]
Can you give me a repro case? I'm not seeing this behavior, at least for simple cases...

**Comment by domenic** [comment]
Seems specific to ending with a closing tag.

```js
"use strict";
const emd = require(".");

emd(`<emu-clause>
  Hello
</emu-clause>`);
```

**Comment by bterlson** [comment]
Thanks, investigating!
